spring:
  datasource:
    jdbc-url: jdbc:h2:mem:archivaldb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  batch:
    jdbc:
      initialize-schema: ALWAYS
  h2:
    console:
      enabled: true

archival:
  postgres:
    jdbc-url: jdbc:postgresql://localhost:5432/postgres
    username: archival
    password: 
    driver-class-name: org.postgresql.Driver
  s3:
    bucket: your-s3-bucket-name
    region: your-aws-region
    access-key: your-access-key
    secret-key: your-secret-key
    base-path: archival/parquet/
  parquet:
    output-dir: /Users/vicky/archival/parquet/
  skip-s3-upload: true

logging:
  level:
    root: INFO
    org.springframework.batch: INFO
    com.app.archivaljob: INFO 