spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/archivaldb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  batch:
    jdbc:
      initialize-schema: always

archival:
  s3:
    bucket: your-s3-bucket-name
    region: your-aws-region
    access-key: your-access-key
    secret-key: your-secret-key
    base-path: archival/parquet/
  parquet:
    # Set this to your desired output directory for Parquet files
    output-dir: /Users/vicky/archival/parquet/  # <-- Replace with your own path

logging:
  level:
    root: INFO
    org.springframework.batch: INFO
    com.app.archivaljob: INFO 